### ISSUE TITLE
getting interviewbit solutions

### ISSUE THREAD

**Issue by vaibhavsood** [cruxrebels/InterviewBit#1]
Hi, can you tell me how you downloaded your solutions from Interviewbit? Did you scrape the website or use any automated method to get your solutions?

**Comment by cruxrebels** [comment]
Hi Vaibhav,

I had build this repository on a daily basis, checking in the solutions which I solved on interviewbit.com, the same day, here. The interviewbit.com website could have been scraped with a simple script if they have provided their website editor APIs anywhere. I am not sure if they have, perhaps you can check on their IRC channel.

Best,
Abhishek
